config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  root to: "public#index"

  resources :subscriptions
  resources :comments, only: [:create], defaults: { format: 'js' }
  get "u/:username" => "public#profile", as: :profile

  resources :communities do
    resources :posts
 end
 
end

app/models/account.rb
class Account < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :subscriptions
  has_many :comments
  has_many :communities, through: :subscriptions


  validates_presence_of :first_name, :last_name, :username

  def full_name
    "#{first_name} #{last_name}"
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :account

    validates_presence_of :message, :account_id, :post_id
    
    
end

app/models/community.rb
class Community < ApplicationRecord
    belongs_to :account
    validates_presence_of :url, :name, :rules
    has_many :posts
    has_many :subscriptions
    has_many :subscribers, through: :subscriptions, source: :account
    validates_presence_of :url, :name, :rules
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :account
    belongs_to :community
    has_many :comments
    validates_presence_of :title, :body, :account_id, :community_id
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    belongs_to :account
    belongs_to :community
end

app/models/vote.rb
 class Vote < ApplicationRecord
    belongs_to :account
    belongs_to :post

    validates_uniqueness_of :account_id, scope: :post_id

    after_create :increment_vote
    after_create :decrement_vote

    private

    def incerement_vote
        field = self.upvote ? :upvotes : :downvotes
        Post.find(self.post_id).increment(field).save
    end

    def decrement_vote
        field = self.upvote ? :upvotes : :downvotes
        Post.find(self.post_id).decrement(field).save
    end
 end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  #### added :username
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])

    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @comment = Comment.new(comment_params)
        @comment.account_id = current_account.id

    respond_to do |format|
            format.js { 
                if @comment.save
                    @comments = Comment.where(post_id: @comment.post_id)
                    render "comments/create"
                else
                    #unable to save
                end
             }
        end
    end

    def comment_params
        params.require(:comment).permit(:message, :post_id)
    end

end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
    before_action :authenticate_account!, except: [ :index, :show]
    before_action :set_community, only: [:show]

    def index
        @communities = Community.all
    end

    def show
     @posts = @community.posts
     @subscriber_count = @community.subscribers.count 
     @is_subscribed = account_signed_in? ? Subscription.where(community_id: @community.id, account_id: current_account.id).any? : false
     @subscription = Subscription.new
    end

    def create
        @community = Community.new(community_values)
        @community.account_id = current_account.id 
        if @community.save
            redirect_to communities_path
        else
            render :new
        end

    end

    def new
        @community = Community.new
    end

    private

    def set_community
        @community = Community.find(params[:id])
    end

    def community_values
        params.require(:community).permit(:name, :url, :summary, :rules)
    end
end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_account!, except: [ :index, :show]
    before_action :set_post, only: [:show]
    before_action :auth_subscriber, only: [:new]

    def index
        @posts = Post.all
    end

    def show
     @comment = Comment.new
    end

    def create
        @post = Post.new(post_values)
        @post.account_id = current_account.id 
        @post.community_id = params[:community_id]
        if @post.save
            redirect_to community_path(@post.community_id)
        else
            @community = Community.find(params[:community_id])
            render :new
        end

    end

    def new
        @community = Community.find(params[:community_id])
        @post = Post.new
    end

    private

    def set_post
        @post = Post.includes(:comments).find(params[:id])
    end

    def auth_subscriber
        unless Subscription.where(community_id: params[:community_id], account_id: current_account.id).any?
            redirect_to root_path, flash: { danger: "You are Not authorized to view this page"}
        end
    end

    def post_values
        params.require(:post).permit(:title, :body)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
    def index
        @communities = Community.all.limit(5)
        @posts = Post.order(id: :desc).limit(20)
    end
    
    def profile
        @profile = Account.find_by_username(params[:username])
        @posts = @profile.posts
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

    def create
        @subscription = Subscription.new(subscription_params)
        @subscription.account_id = current_account.id
        @subscription.save

        redirect_to community_path(@subscription.community_id)
    end

    def subscription_params
        params.require(:subscription).permit(:community_id)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
    def create
        post_id = params[:vote][:post_id]
        vote = Vote.new(vote_params)
        vote.account_id = current_account.id
        exitsting_vote = Vote.where(account_id: current_account.id, post_id: post_id)

        respond_to do |format|
            format.js {
            if exitsting_vote.size > 0
        
                exitsting_vote.first.destroy
            else
                if vote.save
                    @success = true
                else
                    @success = false
                end
                @post = Post.find(post_id)
                @total_upvotes = @post.upvotes
                @total_downvotes = @post.downvotes
            end

            render "votes/create" 
        }
        end
    end

    private

    def vote_params
        params.require(:vote).permit(:upvote, :post_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/create.js.erb
document.getElementById("post-comments").innerHTML = "<%= escape_javascript(render partial: 'posts/comments', locals: { comments: @comments}) %>";

app/views/communities/_form.html.erb
<div class-="row">
    <div class="col-sm-6">
    <%= form_for @community do |form| %>

    <div class="form-group">
        <%= label_tag :name %>
        <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= label_tag :url %>
        <%= form.text_field :url, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= label_tag :summary %>
        <%= form.text_field :summary, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= label_tag :rules %>
        <%= form.text_area :rules, class: "form-control" %>
    </div>

    <%= form.submit "Submit", class: "btn btn-primary" %>
    <%end%>

    </div>
</div>

app/views/communities/_subscribe.html.erb
<%= form_for @subscription do |f| %>
    <%= f.hidden_field :community_id, value: community_id%>
    <%= f.submit "Join Community", class: "btn btn-success float-right"%>
<% end %>

app/views/communities/index.html.erb
<% if account_signed_in? %>

    <div class="float-right">
        <%= link_to  "Create New Community", new_community_path, class: "btn btn-outline-primary" %>
    </div>
<%end%>
 
 
 <% if @communities.size > 0 %>
 <% @communities.each do |community| %>
    <div class="card">
    <h3><%= link_to community.name, community  %></h3>
    <%=simple_format community.rules %>

    </div>

 <%end%>
<%else %>
<p>Still no Communities mate</p>
<% end%>

app/views/communities/new.html.erb
<h2>Create New Community</h2>

<%= render partial: "form" %>

app/views/communities/show.html.erb
<div class="row mb-4">
    <div class="col-sm-8">
    <h3><%= @community.name %></h3>
    </div>
    <div class="col-sm-4">
    <% if @is_subscribed %>
        <%= link_to "Create New Post", new_community_post_path(@community), class: "btn btn-primary float-right" %>
    <% else %>
        <%= render partial: "communities/subscribe", locals: { community_id: @community.id } %>
    <% end %>
    </div>
</div>

<div class="row">
    <div class="col-sm-8">
        <%= render partial: "posts/list", locals: { posts: @posts } %>
    </div>
    <div class="col-sm-4">
        <div class="card p-3">

            <p class="h5">About This Community</p>
            <p class="mt-2"><%= @community.summary %></p>
            <p><%= pluralize @subscriber_count, "member" %></p>
        </div>
    <small>
    <%= simple_format @community.rules %>
    </small>
    </div>
</div>

app/views/layouts/_header.html.erb
<div class="container">
    <div class="row">
        <div class="col-12 pt-3 pd-3">
            <div class="float-right">
            <% if account_signed_in? %>
            <div class="dropdown show">
                <a class="btn btn-white dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= current_account.full_name %>
                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <%= link_to  "Profile", profile_path(current_account.username), class: "dropdown-item" %>
                    <%= link_to  "Settings", edit_account_registration_path, class: "dropdown-item" %>
                    <%= link_to  "Sign Out", destroy_account_session_path, method: :delete, class: "dropdown-item" %>
                </div>
            </div>


            <% else %>
                <%= link_to  "Log In", new_account_session_path, class: "btn btn-outline-primary" %>
                <%= link_to  "Sign In", new_account_registration_path, class: "btn btn-outline-primary" %>
            <%end %>
            </div>
            <p class="h3"><%= link_to "Reddit Clone", root_path %></p>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: "layouts/header" %>
  <section class="bg-light">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 pt-4">
            <%= yield %>
        </div>
      </div>
    </div>
  </section>


    <%= render partial: "layouts/footer" %>
  </body>
</html>

app/views/posts/_comments.html.erb
<% comments.each do |comment| %>
    <div class="comment">
    <%= link_to comment.account.full_name, profile_path(comment.account.username)%>
    <%= simple_format comment.message%>
    </div>
 <% end %>

app/views/posts/_form.html.erb
<div class-="row">
    <div class="col-sm-6">
    <%= form_for [@community, @post] do |p| %>

    <div class="form-group">
        <%= label_tag :title %>
        <%= p.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= label_tag :body %>
        <%= p.text_area :body, class: "form-control" %>
    </div>


    <%= p.submit "Submit", class: "btn btn-primary" %>
    <%end%>

    </div>
</div>

app/views/posts/_list.html.erb
<% posts.each do |post|%>
    <div class="card p-3 mb-3">
        <div class="row">
            <div class="col-1 text-center">
                <div class="fa fa-arrow-up upvote"></div>
                <span class="font-weight-bold">0</span>
                <div class="fa fa-arrow-down downvote"></div>

            </div>
            <div class="col-11">
                    <h4 class="mb-1"><%= link_to post.title, community_post_path(post.community_id, post)%></h4>
                    <p><small><%= link_to post.community.name, community_path(post.community)  %> Posted by <%= link_to post.account.full_name, profile_path(post.account.username) %>, <%= time_ago_in_words post.created_at %> ago. </small></p>
                    <p> <%= truncate post.body, length: 200 %></p>
                 </div>  
            </div>
        </div>
   
 <%end%>   

app/views/posts/edit.html.erb
<h2>Edit your Post</h2>
<%= render partial: "form"%>

app/views/posts/new.html.erb
<h2>Create New Post</h2>
<%= render partial: "form"%>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<%= simple_format @post.body%>

<div id="post-comments">
<%= render partial: "posts/comments", locals: { comments: @post.comments} %>
</div>

<h5>Leave a Comment!</h5>
<%= form_for(@comment, remote: true) do |f|%>
    <%= f.hidden_field :post_id, value: @post.id%>
    <%= f.text_area :message, placeholder: "Your comment goes here!", class: "form-control"%>
    <%= f.submit "Comment", class: "btn btn-success mt-3" %>

<%end%>

app/views/votes/create.js.erb
console.log("vote has been added");